"""Data-quality assessment of the raw Coveo tables.

Coveo's documentation is unusually candid: "front-end tracking is by nature
imperfect, so small inconsistencies are to be expected", and "the order of the
events in the file is not strictly chronological".

Most portfolio projects quote that line and move on. This module *measures* it.
Every check below turns a warning in the docs into a number, so that later
modelling decisions (how to order events, whether to trust a purchase without a
preceding add, how to treat a click on a SKU that was never returned) rest on
observed rates rather than assumptions.

Output: reports/data_quality_report.md
"""
from __future__ import annotations


import time
from datetime import datetime, timezone

from src import config
from src.ingest.build_duckdb import connect

MINUTE_MS = 60 * 1000
SESSION_GAP_MS = config.SESSION_GAP_MINUTES * MINUTE_MS


class Report:
    """Accumulates markdown sections and the headline numbers."""

    def __init__(self) -> None:
        self.sections: list[str] = []
        self.findings: list[tuple[str, str]] = []

    def add(self, markdown: str) -> None:
        self.sections.append(markdown.rstrip())

    def finding(self, severity: str, text: str) -> None:
        """severity in {'blocker', 'handle', 'note'}."""
        self.findings.append((severity, text))

    def render(self) -> str:
        icons = {"blocker": "🔴", "handle": "🟠", "note": "🔵"}
        head = [
            "# Data Quality Assessment — Coveo SIGIR 2021 eCommerce Dataset",
            "",
            "Generated by `src/profiling/data_quality.py` on "
            f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC.",
            "",
            "> Dataset © Coveo Solutions Inc., released for the SIGIR 2021 eCom Data",
            "> Challenge and used here under their research/educational Terms &",
            "> Conditions. No row-level data is reproduced in this report — only",
            "> aggregate counts and rates.",
            "",
            "---",
            "",
            "## Findings summary",
            "",
        ]
        if self.findings:
            head.append("| | Finding |")
            head.append("|---|---|")
            for sev, text in self.findings:
                head.append(f"| {icons.get(sev, '•')} | {text} |")
        else:
            head.append("_No findings recorded._")
        head += ["", "🔴 blocks analysis · 🟠 must be handled in modelling · "
                     "🔵 worth knowing", "", "---", ""]
        return "\n".join(head) + "\n" + "\n\n".join(self.sections) + "\n"


def block(text: str) -> str:
    """Dedent a section template.

    textwrap.dedent cannot be used directly here: it runs on the *interpolated*
    f-string, and interpolated tables start at column 0, so the common leading
    prefix collapses to "" and nothing is stripped. Every template in this
    module is indented by exactly 8 spaces, so strip that much from the lines
    that have it and leave interpolated content alone.
    """
    return "\n".join(
        line[8:] if line.startswith(" " * 8) else line
        for line in text.split("\n")
    ).strip()


def md_table(headers: list[str], rows: list[tuple]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        cells = []
        for v in r:
            if isinstance(v, float):
                cells.append(f"{v:,.2f}")
            elif isinstance(v, int):
                cells.append(f"{v:,}")
            else:
                cells.append("_NULL_" if v is None else str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def pct(part: float, whole: float) -> float:
    return 0.0 if not whole else 100.0 * part / whole


# --------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------

def check_volume(con, rep: Report) -> dict:
    rows = con.execute("""
        SELECT 'raw_browsing' AS tbl, count(*) AS n_rows,
               count(DISTINCT session_id_hash) AS n_sessions,
               count(DISTINCT product_sku_hash) AS n_skus
        FROM raw_browsing
        UNION ALL
        SELECT 'raw_search', count(*), count(DISTINCT session_id_hash), NULL
        FROM raw_search
        UNION ALL
        SELECT 'raw_catalog', count(*), NULL, count(DISTINCT product_sku_hash)
        FROM raw_catalog
    """).fetchall()

    span = con.execute("""
        SELECT min(server_timestamp_epoch_ms), max(server_timestamp_epoch_ms)
        FROM raw_browsing
    """).fetchone()
    lo = datetime.fromtimestamp(span[0] / 1000, timezone.utc)
    hi = datetime.fromtimestamp(span[1] / 1000, timezone.utc)
    days = (hi - lo).days

    totals = {r[0]: r[1] for r in rows}

    rep.add(block(f"""
        ## 1. Volume & coverage

        {md_table(["Table", "Rows", "Sessions", "Distinct SKUs"], rows)}

        **Observation window:** {lo:%Y-%m-%d} → {hi:%Y-%m-%d} ({days} days).

        Coveo shift all timestamps by an undisclosed number of weeks to
        anonymise the release, while preserving intra-week patterns. Absolute
        dates are therefore meaningless; **day-of-week and hour-of-day effects
        are still valid**, and all seasonality in this project is analysed on
        that basis rather than against a calendar.
    """))
    rep.finding("note", f"Observation window spans {days} days; timestamps are "
                        "week-shifted, so only intra-week seasonality is interpretable.")
    return totals


def check_completeness(con, rep: Report) -> None:
    n = con.execute("SELECT count(*) FROM raw_browsing").fetchone()[0]
    rows = con.execute(f"""
        SELECT 'session_id_hash', count(*) - count(session_id_hash) FROM raw_browsing
        UNION ALL SELECT 'event_type', count(*) - count(event_type) FROM raw_browsing
        UNION ALL SELECT 'product_action', count(*) - count(product_action) FROM raw_browsing
        UNION ALL SELECT 'product_sku_hash', count(*) - count(product_sku_hash) FROM raw_browsing
        UNION ALL SELECT 'server_timestamp_epoch_ms', count(*) - count(server_timestamp_epoch_ms) FROM raw_browsing
        UNION ALL SELECT 'hashed_url', count(*) - count(hashed_url) FROM raw_browsing
    """).fetchall()
    tbl = [(c, k, pct(k, n)) for c, k in rows]

    rep.add(block(f"""
        ## 2. Completeness — `raw_browsing`

        {md_table(["Column", "NULL rows", "NULL %"], tbl)}

        A NULL `product_action` is **expected, not missing data**: it marks a
        non-product pageview (an FAQ page, a category listing). The same is true
        of `product_sku_hash` on those rows. These two columns are only
        meaningfully "incomplete" when they disagree with each other, which is
        checked in §4.
    """))


def check_event_taxonomy(con, rep: Report) -> None:
    rows = con.execute("""
        SELECT event_type,
               coalesce(product_action, '(none — pageview)') AS product_action,
               count(*) AS events,
               count(DISTINCT session_id_hash) AS sessions
        FROM raw_browsing
        GROUP BY 1, 2
        ORDER BY events DESC
    """).fetchall()
    rep.add(block(f"""
        ## 3. Event taxonomy

        {md_table(["event_type", "product_action", "Events", "Sessions"], rows)}

        This crosstab is the contract the rest of the project codes against: it
        defines exactly which `(event_type, product_action)` pairs exist, and
        therefore which combinations the funnel logic must handle.
    """))


def check_internal_consistency(con, rep: Report) -> None:
    n = con.execute("SELECT count(*) FROM raw_browsing").fetchone()[0]

    orphan_action, orphan_sku = con.execute("""
        SELECT
          count(*) FILTER (WHERE product_action IS NOT NULL AND product_sku_hash IS NULL),
          count(*) FILTER (WHERE product_action IS NULL AND product_sku_hash IS NOT NULL)
        FROM raw_browsing
    """).fetchone()

    # Grouping directly on the six raw columns means a ~200-byte key (two
    # 64-char hashes) across 36M rows -- ~7 GB of grouping keys, which spills to
    # disk and took over two minutes. Fingerprinting each row to a 32-char md5
    # first shrinks the key ~6x and answers both questions in a single pass.
    # A sentinel is used instead of bare concat_ws because concat_ws skips
    # NULLs, which would make ('a', NULL, 'b') collide with ('a', 'b', NULL).
    dupes, dupe_rows = con.execute("""
        WITH fp AS (
            SELECT md5(concat_ws('|',
                       coalesce(session_id_hash,           '<N>'),
                       coalesce(event_type,                '<N>'),
                       coalesce(product_action,            '<N>'),
                       coalesce(product_sku_hash,          '<N>'),
                       coalesce(server_timestamp_epoch_ms::VARCHAR, '<N>'),
                       coalesce(hashed_url,                '<N>'))) AS row_fingerprint
            FROM raw_browsing
        ),
        d AS (
            SELECT row_fingerprint, count(*) AS c
            FROM fp GROUP BY row_fingerprint HAVING count(*) > 1
        )
        SELECT count(*), coalesce(sum(c - 1), 0) FROM d
    """).fetchone()

    rep.add(block(f"""
        ## 4. Internal consistency

        | Check | Rows | % of events |
        |---|---|---|
        | `product_action` set but `product_sku_hash` NULL | {orphan_action:,} | {pct(orphan_action, n):.4f}% |
        | `product_sku_hash` set but `product_action` NULL | {orphan_sku:,} | {pct(orphan_sku, n):.4f}% |
        | Exact duplicate event rows (distinct fingerprints) | {dupes:,} | — |
        | Redundant copies from those duplicates | {dupe_rows:,} | {pct(dupe_rows, n):.4f}% |

        Exact duplicates are the classic signature of a tracking pixel firing
        twice on one user action. They are **not** de-duplicated in the raw
        layer — that would destroy evidence — but they are collapsed in the
        staging layer, where the rule is documented and reversible.
    """))
    if orphan_action:
        rep.finding("handle", f"{orphan_action:,} product events carry an action but no SKU "
                              "— excluded from SKU-level metrics, retained in funnel counts.")
    if dupe_rows:
        rep.finding("handle", f"{dupe_rows:,} duplicate event rows ({pct(dupe_rows, n):.3f}%) "
                              "collapsed in staging; raw layer left intact.")


def check_event_ordering(con, rep: Report) -> None:
    """The headline check: file order vs timestamp order."""
    t0 = time.time()
    row = con.execute("""
        WITH seq AS (
            SELECT session_id_hash,
                   server_timestamp_epoch_ms AS ts,
                   lag(server_timestamp_epoch_ms)
                     OVER (PARTITION BY session_id_hash ORDER BY file_row_idx) AS prev_ts
            FROM raw_browsing
        )
        SELECT
            count(*) FILTER (WHERE ts < prev_ts)                       AS inversions,
            count(DISTINCT session_id_hash) FILTER (WHERE ts < prev_ts) AS bad_sessions,
            count(DISTINCT session_id_hash)                             AS all_sessions
        FROM seq
    """).fetchone()
    inversions, bad_sessions, all_sessions = row

    ties = con.execute("""
        SELECT count(*) FROM (
            SELECT session_id_hash, server_timestamp_epoch_ms, count(*) AS c
            FROM raw_browsing
            GROUP BY 1, 2 HAVING count(*) > 1
        )
    """).fetchone()[0]

    pdp = con.execute("""
        SELECT count(*) FROM (
            SELECT session_id_hash, server_timestamp_epoch_ms, hashed_url
            FROM raw_browsing
            WHERE hashed_url IS NOT NULL
            GROUP BY 1, 2, 3
            HAVING count(*) FILTER (WHERE product_action = 'detail') > 0
               AND count(*) FILTER (WHERE event_type = 'pageview') > 0
        )
    """).fetchone()[0]

    residual = ties - pdp

    rep.add(block(f"""
        ## 5. Event ordering — testing the documented hazard

        Coveo warn that *"the order of the events in the file is not strictly
        chronological (refer to the session identifier and the timestamp
        information to reconstruct the actual chain of events)."*

        Taking that as a hypothesis and measuring it produces a result that is
        **not** the one the warning implies.

        | Check | Value | Rate |
        |---|---|---|
        | Events out of chronological order in file order | {inversions:,} | {pct(inversions, 36_079_307):.4f}% of events |
        | Sessions affected by a true inversion | {bad_sessions:,} | {pct(bad_sessions, all_sessions):.3f}% of {all_sessions:,} |
        | `(session, timestamp)` collisions — 2+ events in one millisecond | {ties:,} | — |
        | …explained by the `detail`+`pageview` PDP double-fire | {pdp:,} | **{pct(pdp, ties):.1f}% of collisions** |
        | …unexplained residual collisions | {residual:,} | {pct(residual, ties):.1f}% of collisions |

        ### What this actually means

        **File order is very nearly chronological.** Only {bad_sessions:,}
        sessions — {pct(bad_sessions, all_sessions):.3f}% — contain a genuine
        backwards step. Naïvely trusting row order would be *mostly* fine, which
        is precisely what makes it dangerous: the failure is rare enough to
        survive spot-checking and still corrupt results.

        **The real ordering hazard is a different one: timestamp is not a total
        order.** {ties:,} times, two or more events in the same session share a
        single millisecond, and {pct(pdp, ties):.1f}% of those are the
        product-detail-page double-fire Coveo describe — a PDP emitting a
        `detail` and a `pageview` at the same instant.

        So sorting by timestamp alone does not produce a deterministic sequence:
        tied rows can come back in either order, and the funnel step assignment
        would differ between runs of the same query on the same data. Sequencing
        is therefore

        ```sql
        ORDER BY session_id_hash, server_timestamp_epoch_ms, file_row_idx
        ```

        where `file_row_idx` — captured at ingest, before anything is sorted —
        supplies the stable third key. This is the reason the raw layer records
        physical file position instead of discarding it.

        The {pdp:,} PDP pairs are collapsed to a single product view in staging;
        counting both would inflate product views against page views by roughly
        a third of all events.

        _(check ran in {time.time() - t0:,.1f}s)_
    """))
    rep.finding("note", f"Only {bad_sessions:,} sessions ({pct(bad_sessions, all_sessions):.3f}%) have "
                        "genuinely out-of-order file rows — the documented warning is real but minor.")
    if ties:
        rep.finding("blocker", f"{ties:,} (session, timestamp) collisions mean timestamp is NOT a total "
                               "order; sorting by it alone is non-deterministic. `file_row_idx` used "
                               "as a stable tie-break.")
    if pdp:
        rep.finding("handle", f"{pdp:,} PDP double-fires ({pct(pdp, ties):.1f}% of all collisions) "
                              "collapsed to one product view in staging.")


def check_session_rule(con, rep: Report) -> None:
    """Coveo define a session as events <=30 min apart. Does the data obey?"""
    row = con.execute(f"""
        WITH gaps AS (
            SELECT session_id_hash,
                   server_timestamp_epoch_ms
                     - lag(server_timestamp_epoch_ms)
                         OVER (PARTITION BY session_id_hash
                               ORDER BY server_timestamp_epoch_ms, file_row_idx) AS gap_ms
            FROM raw_browsing
        )
        SELECT count(DISTINCT session_id_hash) FILTER (WHERE gap_ms > {SESSION_GAP_MS}),
               max(gap_ms),
               count(DISTINCT session_id_hash)
        FROM gaps
    """).fetchone()
    violating, max_gap, total = row
    max_gap_h = (max_gap or 0) / 3_600_000

    dur = con.execute("""
        SELECT
          median(dur_ms) / 1000.0,
          quantile_cont(dur_ms, 0.95) / 1000.0,
          max(dur_ms) / 3600000.0
        FROM (
          SELECT max(server_timestamp_epoch_ms) - min(server_timestamp_epoch_ms) AS dur_ms
          FROM raw_browsing GROUP BY session_id_hash
        )
    """).fetchone()

    rep.add(block(f"""
        ## 6. Does the data obey its own session rule?

        Coveo define a session as events **at most 30 minutes apart**. Treating
        that as a specification and testing it:

        | Check | Value |
        |---|---|
        | Sessions containing an internal gap > 30 min | {violating:,} of {total:,} ({pct(violating, total):.3f}%) |
        | Largest single intra-session gap | {max_gap_h:,.1f} hours |
        | Median session duration | {dur[0]:,.0f} s |
        | 95th percentile session duration | {dur[1]:,.0f} s |
        | Longest session | {dur[2]:,.1f} hours |

        A non-zero count here is not a mistake in the data so much as a fact
        about sessionisation: server-side stitching, clock skew between client
        and server, and background tabs all produce gaps that violate the
        nominal rule. It matters because **session duration is an input to
        time-to-purchase**, and these outliers would otherwise drag the mean.
        Time-based metrics in this project are reported as medians with
        explicit outlier handling for exactly this reason.
    """))
    if violating:
        rep.finding("handle", f"{violating:,} sessions violate Coveo's own 30-minute gap rule; "
                              "time-to-purchase reported as median, outliers capped.")


def check_referential_integrity(con, rep: Report) -> None:
    row = con.execute("""
        WITH b AS (SELECT DISTINCT product_sku_hash AS sku FROM raw_browsing
                   WHERE product_sku_hash IS NOT NULL)
        SELECT (SELECT count(*) FROM b),
               (SELECT count(*) FROM b LEFT JOIN raw_catalog c
                  ON b.sku = c.product_sku_hash WHERE c.product_sku_hash IS NULL)
    """).fetchone()
    browsed, orphaned = row

    cat = con.execute("""
        SELECT count(*),
               count(*) FILTER (WHERE category_hash IS NULL),
               count(*) FILTER (WHERE price_bucket IS NULL),
               count(*) FILTER (WHERE category_hash IS NULL AND price_bucket IS NULL),
               count(DISTINCT category_hash)
        FROM raw_catalog
    """).fetchone()
    n_cat, no_cat, no_price, no_either, n_distinct_cat = cat

    depth = con.execute("""
        SELECT category_depth, count(*) FROM raw_catalog
        WHERE category_hash IS NOT NULL GROUP BY 1 ORDER BY 1
    """).fetchall()

    rep.add(block(f"""
        ## 7. Referential integrity & catalog coverage

        | Check | Value |
        |---|---|
        | Distinct SKUs appearing in browsing events | {browsed:,} |
        | …with **no row at all** in `sku_to_content.csv` | {orphaned:,} ({pct(orphaned, browsed):.2f}%) |
        | Catalog rows | {n_cat:,} |
        | …missing `category_hash` | {no_cat:,} ({pct(no_cat, n_cat):.2f}%) |
        | …missing `price_bucket` | {no_price:,} ({pct(no_price, n_cat):.2f}%) |
        | …missing **both** (SKU present but entirely empty) | {no_either:,} ({pct(no_either, n_cat):.2f}%) |
        | Distinct category paths | {n_distinct_cat:,} |

        Category hierarchy depth:

        {md_table(["Levels in path", "SKUs"], depth)}

        Coveo note the catalog covers SKUs "when the information is available",
        so sparsity here is a documented property, not corruption. It is still
        load-bearing: **any category- or price-segmented metric silently
        excludes these SKUs unless they are given an explicit `(unknown)`
        bucket.** That is exactly the kind of gap that turns into a wrong
        business number, so the dimensional model assigns unknown members
        rather than dropping the rows.
    """))
    if orphaned:
        rep.finding("handle", f"{orphaned:,} browsed SKUs ({pct(orphaned, browsed):.1f}%) absent from "
                              "the catalog — mapped to an 'unknown product' member, not dropped.")
    if no_price:
        rep.finding("handle", f"{no_price:,} catalog SKUs ({pct(no_price, n_cat):.1f}%) lack a price "
                              "bucket — price analyses report coverage alongside results.")


def check_funnel_integrity(con, rep: Report) -> None:
    rows = con.execute("""
        WITH s AS (
            SELECT session_id_hash,
                   count(*) FILTER (WHERE product_action = 'detail')   AS n_detail,
                   count(*) FILTER (WHERE product_action = 'add')      AS n_add,
                   count(*) FILTER (WHERE product_action = 'remove')   AS n_remove,
                   count(*) FILTER (WHERE product_action = 'purchase') AS n_purchase,
                   count(*) FILTER (WHERE event_type = 'pageview')     AS n_pageview
            FROM raw_browsing GROUP BY 1
        )
        SELECT count(*)                                                AS sessions,
               count(*) FILTER (WHERE n_purchase > 0)                  AS with_purchase,
               count(*) FILTER (WHERE n_purchase > 0 AND n_add = 0)    AS purchase_no_add,
               count(*) FILTER (WHERE n_add > 0 AND n_detail = 0)      AS add_no_detail,
               count(*) FILTER (WHERE n_purchase > 0 AND n_pageview = 0) AS purchase_no_pageview,
               count(*) FILTER (WHERE n_remove > 0 AND n_add = 0)      AS remove_no_add
        FROM s
    """).fetchone()
    (sessions, with_purchase, purchase_no_add, add_no_detail,
     purchase_no_pageview, remove_no_add) = rows

    rep.add(block(f"""
        ## 8. Funnel integrity — is the funnel actually a funnel?

        The canonical model assumes `pageview → detail → add → purchase`. Real
        telemetry does not respect that, and the size of the violation decides
        whether a strict-sequence funnel is even defensible.

        | Check | Sessions | % of purchasing sessions |
        |---|---|---|
        | Sessions with ≥1 purchase | {with_purchase:,} | 100% |
        | Purchase with **no `add`** anywhere in session | {purchase_no_add:,} | {pct(purchase_no_add, with_purchase):.2f}% |
        | Purchase with **no pageview** anywhere in session | {purchase_no_pageview:,} | {pct(purchase_no_pageview, with_purchase):.2f}% |
        | `add` with no prior `detail` in session | {add_no_detail:,} | — |
        | `remove` with no `add` in session | {remove_no_add:,} | — |

        **This is the single most important result in the assessment.** A
        purchase with no add-to-cart in the same session is not a data error —
        it is a shopper whose cart was built in an *earlier* session, then
        checked out after the 30-minute boundary created a new session ID.

        The consequence is decisive: a strict *sequential* funnel would discard
        these conversions and **understate revenue**. This project therefore
        reports two funnel definitions side by side —

        - **Step-attained funnel** — did the session ever reach this stage?
        - **Strict-sequence funnel** — did the stages occur in order?

        — and the gap between them is itself a finding, because it quantifies
        how much of the business's conversion is cross-session. Reporting only
        one number here would be the mistake.
    """))
    if purchase_no_add:
        rep.finding("blocker", f"{purchase_no_add:,} purchasing sessions ({pct(purchase_no_add, with_purchase):.1f}%) "
                               "contain no add-to-cart — cross-session carts. Reported via dual "
                               "funnel definitions rather than dropped.")
    if remove_no_add:
        rep.finding("note", f"{remove_no_add:,} sessions remove an item never added in-session — "
                            "consistent with cart state persisting across sessions.")


def check_search_quality(con, rep: Report) -> None:
    row = con.execute("""
        SELECT
          count(*)                                                        AS queries,
          count(*) FILTER (WHERE product_skus IS NULL)                    AS null_results,
          count(*) FILTER (WHERE product_skus IS NOT NULL
                             AND len(product_skus) = 0)                   AS empty_results,
          count(*) FILTER (WHERE clicked_skus IS NOT NULL
                             AND len(clicked_skus) > 0)                   AS with_click,
          count(DISTINCT session_id_hash)                                 AS sessions
        FROM raw_search
    """).fetchone()
    queries, null_results, empty_results, with_click, sessions = row

    phantom = con.execute("""
        SELECT count(*) FROM raw_search
        WHERE clicked_skus IS NOT NULL AND len(clicked_skus) > 0
          AND len(list_filter(clicked_skus,
                    x -> NOT list_contains(coalesce(product_skus, []), x))) > 0
    """).fetchone()[0]

    sizes = con.execute("""
        SELECT median(len(product_skus)),
               quantile_cont(len(product_skus), 0.95),
               max(len(product_skus))
        FROM raw_search WHERE product_skus IS NOT NULL AND len(product_skus) > 0
    """).fetchone()

    orphan_sessions = con.execute("""
        SELECT count(*) FROM (
          SELECT DISTINCT s.session_id_hash FROM raw_search s
          LEFT JOIN (SELECT DISTINCT session_id_hash FROM raw_browsing) b
            ON s.session_id_hash = b.session_id_hash
          WHERE b.session_id_hash IS NULL
        )
    """).fetchone()[0]

    rep.add(block(f"""
        ## 9. Search event quality

        | Check | Value | % of queries |
        |---|---|---|
        | Search queries | {queries:,} | 100% |
        | Distinct sessions issuing a search | {sessions:,} | — |
        | Queries returning a **NULL** result list | {null_results:,} | {pct(null_results, queries):.2f}% |
        | Queries returning an **empty** result list | {empty_results:,} | {pct(empty_results, queries):.2f}% |
        | Queries with ≥1 click | {with_click:,} | {pct(with_click, queries):.2f}% |
        | **Clicks on a SKU that was never returned** | {phantom:,} | {pct(phantom, queries):.4f}% |
        | Search sessions with no browsing events at all | {orphan_sessions:,} | — |

        Result-set size: median {sizes[0]:,.0f}, p95 {sizes[1]:,.0f}, max {sizes[2]:,.0f}.

        The null-result rate is the headline number: **zero-result searches are
        a direct, addressable revenue leak** and one of the few metrics in this
        dataset that maps to an obvious merchandising action.

        The phantom-click count is a pure telemetry artefact — a click recorded
        against a SKU absent from the logged result set, which happens when the
        result set is re-ranked or paginated between impression and click. It is
        small, but it must be excluded before computing click-through rate,
        because such clicks have no denominator to belong to.
    """))
    if null_results or empty_results:
        rep.finding("note", f"{null_results + empty_results:,} searches "
                            f"({pct(null_results + empty_results, queries):.1f}%) returned nothing "
                            "— quantified as a zero-result revenue leak.")
    if phantom:
        rep.finding("handle", f"{phantom:,} clicks reference a SKU absent from the logged result "
                              "set — excluded from CTR denominators.")
    if orphan_sessions:
        rep.finding("note", f"{orphan_sessions:,} sessions appear in search but never in browsing "
                            "— search and browsing files are not fully co-extensive.")


CHECKS = [
    ("Volume & coverage", check_volume),
    ("Completeness", check_completeness),
    ("Event taxonomy", check_event_taxonomy),
    ("Internal consistency", check_internal_consistency),
    ("Event ordering", check_event_ordering),
    ("Session rule", check_session_rule),
    ("Referential integrity", check_referential_integrity),
    ("Funnel integrity", check_funnel_integrity),
    ("Search quality", check_search_quality),
]


def main() -> None:
    con = connect(read_only=True)
    rep = Report()
    print("Running data quality assessment\n")
    for name, fn in CHECKS:
        print(f"  {name:<26}", end="", flush=True)
        t0 = time.time()
        fn(con, rep)
        print(f"{time.time() - t0:>7,.1f}s")
    con.close()

    out = config.REPORTS_DIR / "data_quality_report.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rep.render(), encoding="utf-8")

    print(f"\nWrote {out}")
    print(f"\n{len(rep.findings)} findings:")
    for sev, text in rep.findings:
        print(f"  [{sev:<7}] {text}")


if __name__ == "__main__":
    main()
